import 'src/app/globals.css';
import { Inter } from 'next/font/google';
import GlobalNavbar from 'src/components/global-navbar';
import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalNavbar />
        <div className="mx-auto min-h-screen max-w-2xl space-y-8 bg-white pb-4 pt-20 shadow-lg shadow-black/10">
          {children}
        </div>
      </body>
    </html>
  );
}
